[platformio]
src_dir = .
include_dir = .
test_dir = Core/Test
default_envs = release

[env:release]
platform = ststm32
upload_protocol = stlink
debug_tool = stlink
platform_packages =
  toolchain-gccarmnoneeabi@=1.140201.0
monitor_speed = 115200

board = nucleo_c031c6
board_build.ldscript = STM32C031XX_FLASH.ld

build_flags =
    -std=gnu23
    -D_XOPEN_SOURCE
    -DUSE_HAL_DRIVER
    -ICore/Inc
    -ICore/Inc/rec/module_name
    -ICore/Inc/rec/temperature
    -IDrivers/CMSIS/Include/
    -IDrivers/STM32C0xx_HAL_Driver/Inc/
    -IDrivers/STM32C0xx_HAL_Driver/Inc/Legacy/
    -IDrivers/CMSIS/Device/ST/STM32C0xx/Include/

build_src_filter =
    +<Core/Src/>
    +<Drivers/STM32C0xx_HAL_Driver/Src/>
    -<Drivers/STM32C0xx_HAL_Driver/Src/*_template.c>
    +<./startup_stm32c031xx.s>

lib_deps =
    https://github.com/eagletrt/libtimebase-sw#dev
    https://github.com/eagletrt/libfsm-sw#dev

check_tool = clangtidy
check_flags =
    clangtidy: --checks=-*,cert-*,clang-analyzer-*,bugprone-*,performance-*,readability-*,-bugprone-easily-swappable-parameters
    clangtidy: --warnings-as-errors=clang-analyzer-*,bugprone-*
    clangtidy: --header-filter=^.*Core/(Inc|Src)/.+/[^/]+\.(c|h)$
    clangtidy: --system-headers=false
check_src_filters =
    -<**>
    ; Add here the directories you want to check with clang-tidy

[env:tests]
platform = native
test_framework = unity
test_build_src = true
build_flags =
    -std=gnu23
    -DEAGLETRT_STATIC=
    -lm ;link math.h
    -D_XOPEN_SOURCE
    -ICore/Inc/rec/module_name
    -ICore/Inc/rec/temperature
    -ICore/Test/include

build_src_filter =
    +<Core/Src/rec/temperature/>
    +<Core/Src/rec/module_name/>

lib_deps =
    https://github.com/eagletrt/libtimebase-sw#dev
    https://github.com/eagletrt/libfsm-sw#dev
